#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove Old MOTD
      file: 'path={{item}} state=absent'
      with_items:
        - /etc/update-motd.d

    - name: Deploy Dynamic MOTD
      file:
        path: /etc/update-motd.d
        state: directory
        mode: 0775

    #- name: Import Support Files
    #  copy: "src={{item}} dest=/etc/update-motd.d/{{item}} force=yes mode=0775"
    #  with_items:
    #    - 00-header
    #    - 10-sysinfo
    #    - 90-footer

    - name: Import Support Files
      copy: 'src={{item}} dest=/etc/update-motd.d/{{item}} force=yes mode=0775'
      with_items:
        - 10-hostname-color
        - 20-sysinfo
        - 30-diskinfo
        - 40-services
        - 60-docker
        - 90-footer

    # - name: Symlink
    #   file:
    #     src: /var/run/motd
    #     dest: /etc/mot
    #     state: link
    #     force: yes

    # - name: Npm Mods
    #   npm: 'name={{item}} global=yes'
    #   with_items:
    #     - frontail

    - name: Install lolcat pip module
      pip:
        name: lolcat
        state: latest
      ignore_errors: yes

    - cron:
        name: 'Update MOTD'
        user: 'root'
        minute: '10'
        job: 'update-motd'
        state: present
      become_user: root
