#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: true
  tasks:

  - name: Install Common Packages (Takes Awhile)
    apt: "name={{item}} state=present"
    with_items:
      - fuse
      - nano
      - fail2ban
      - wget
      - lsb-release
      - figlet
      - update-notifier-common
      - unionfs-fuse
      - software-properties-common
      - unrar
      - unzip
      - glances
      - python-pip
      - python3-pip
      - python-passlib
      - zip
      - curl
      - man-db
      - htop
      - openssh-server
      - dirmngr
      - npm
      - zip
      - apt-transport-https
      - ca-certificates
      - tree
      - ncdu
      - ctop
      - dialog
      - dnsutils
      - mc
      - apache2-utils
      - lsof
      - pwgen
      - gawk
      - python-lxml
      - acl
      - bc
    #ignore_errors: yes
