---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: Register User
      shell: 'cat /var/plexguide/boxcore.user'
      register: boxuser

    - name: Register Branch
      shell: 'cat /var/plexguide/boxcore.branch'
      register: boxbranch

    - name: 'Cloning {{boxuser.stdout}} Core Apps'
      git:
        repo: 'https://github.com/{{boxuser.stdout}}/PlexGuide-PGPress'
        dest: '/opt/pgpress'
        version: '{{boxbranch.stdout}}'
        force: yes
